#
# GNUmakefile for target FontBook
# begin - generated by buildtool, please don't modify
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = FontBook

FontBook_OBJC_FILES = FontBook/GoogleFontsController.m \
	FontBook/main.m \
	FontBook/AppDelegate.m 

FontBook_RESOURCE_FILES = FontBook/Base.lproj/MainMenu.xib \
	FontBook/Assets.xcassets \
	font_book-48x48.png \
	FontBookInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./FontBook 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble

#
# end - generated makefile
#
